.EQU AJU = PB0
.EQU SEL = PB1
    
setup:
    ;CONFIG. LEDS COMO SAÍDA
    LDI R16, 0b1111_1111
    OUT DDRD, R16
    ;CONFIG. PINOS DOS BOTÕES COMO ENTRADA
    CBI DDRB, AJU
    CBI DDRB, SEL
    ; ... ATIVAR PULL UP
    SBI PORTB, AJU
    SBI PORTB, SEL
    
main:
    SBIC  PINB, AJU
    RJMP AJU_NPRESS
AJU_PRESS:
    SBI PORTD, PD0
    SBI PORTD, PD1
    SBI PORTD, PD2
    SBI PORTD, PD3
    RJMP   AJU_FIM
AJU_NPRESS:    
    CBI PORTD, PD0
    CBI PORTD, PD1
    CBI PORTD, PD2
    CBI PORTD, PD3
AJU_FIM:
    SBIC  PINB, SEL
    RJMP SEL_NPRESS
SEL_PRESS:
    SBI PORTD, PD4
    SBI PORTD, PD5
    SBI PORTD, PD6
    SBI PORTD, PD7
    RJMP   SEL_FIM
SEL_NPRESS:    
    CBI PORTD, PD4
    CBI PORTD, PD5
    CBI PORTD, PD6
    CBI PORTD, PD7
SEL_FIM:    
   RJMP main